/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package colla.appl.developer_viewer.view;

import colla.dfs.app.SearchWords;
import colla.kernel.util.Debugger;
import java.io.File;
import javax.swing.JFileChooser;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;

/**
 *
 * @author dmatos
 */
public class DFSInternalWindow extends javax.swing.JInternalFrame {

    /**
     * Creates new form DFSInternalWindow
     */
    public DFSInternalWindow() {
        super("Distributed File System", true, true, true, true);
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.jFileChooser = new JFileChooser();
        this.jFileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        this.jTextFieldFileChooser.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldFileChooser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneDFSResults = new javax.swing.JTextPane();
        jTextFieldWordToSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 300));

        jTextFieldFileChooser.setEditable(false);
        jTextFieldFileChooser.setText(org.openide.util.NbBundle.getMessage(DFSInternalWindow.class, "DFSInternalWindow.jTextFieldFileChooser.text")); // NOI18N
        jTextFieldFileChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldFileChooserMouseClicked(evt);
            }
        });
        jTextFieldFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFileChooserActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(DFSInternalWindow.class, "DFSInternalWindow.jLabel1.text")); // NOI18N

        jTextPaneDFSResults.setEditable(false);
        jScrollPane1.setViewportView(jTextPaneDFSResults);

        jTextFieldWordToSearch.setText(org.openide.util.NbBundle.getMessage(DFSInternalWindow.class, "DFSInternalWindow.jTextFieldWordToSearch.text")); // NOI18N
        jTextFieldWordToSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldWordToSearchKeyTyped(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(DFSInternalWindow.class, "DFSInternalWindow.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(DFSInternalWindow.class, "DFSInternalWindow.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldFileChooser)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 347, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldWordToSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldWordToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFileChooserActionPerformed
        this.openFileChooser();
    }//GEN-LAST:event_jTextFieldFileChooserActionPerformed

    private void jTextFieldFileChooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldFileChooserMouseClicked
        this.openFileChooser();
    }//GEN-LAST:event_jTextFieldFileChooserMouseClicked

    private void jTextFieldWordToSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldWordToSearchKeyTyped
        if(evt.getKeyChar() == '\n'){
            this.executeSearch();
        }
    }//GEN-LAST:event_jTextFieldWordToSearchKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.executeSearch();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void openFileChooser() {

        this.jFileChooser.setAcceptAllFileFilterUsed(true);
        this.jFileChooser.setDialogTitle("Select a path to perform a search");
        int returnFileChooser = jFileChooser.showOpenDialog(this);
        if (returnFileChooser == JFileChooser.APPROVE_OPTION) {
            fileToSearch = jFileChooser.getSelectedFile();
            //clearTaskFields();            
        }
        this.jTextFieldFileChooser.setText(fileToSearch.getPath());
    }
    
    private void executeSearch(){
        String result = "";
        String filePath = "";
        if(fileToSearch != null)
            filePath = fileToSearch.getPath();
        String word = jTextFieldWordToSearch.getText();
        if(jTextFieldFileChooser.getText().length() > 0 &&
                jTextFieldWordToSearch.getText().length() > 0){
            SearchWords searchWords = new SearchWords();
            try {
                result = searchWords.executeSearch(filePath, word);
                this.jTextPaneDFSResults.setText(result);
            } catch (Exception ex) {
                Debugger.debug(ex);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DFSInternalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DFSInternalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DFSInternalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DFSInternalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DFSInternalWindow().setVisible(true);
            }
        });
    }
    private File fileToSearch;
    private JFileChooser jFileChooser;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldFileChooser;
    private javax.swing.JTextField jTextFieldWordToSearch;
    private javax.swing.JTextPane jTextPaneDFSResults;
    // End of variables declaration//GEN-END:variables
}
